apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-test
  template:
    metadata:
      labels:
        app: django-test
    spec:
      containers:
      - name: django-test
        image: wha02068/django-test:v21
        ports:
        - containerPort: 8000
