apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-test
  template:
    metadata:
      labels:
        app: django-test
    spec:
      nodeSelector:
        role: django
      containers:
      - name: django-test
        image: wha02068/django-test:v1.0.12
        ports:
        - containerPort: 8000

        volumeMounts:
        - name: sqlite-storage
          mountPath: /app/data   # SQLite 저장 위치

      volumes:
      - name: sqlite-storage
        persistentVolumeClaim:
          claimName: sqlite-pvc
