apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django
spec:
  type: ClusterIP
  selector:
    app: django
  ports:
    - port: 8000        # 클러스터 내부 포트
      targetPort: 8000  # Django 컨테이너 포트
